# -*- coding: utf-8 -*-
"""levels of inheritance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qvZD1bA2hcBw_oFV_6eytaFYjVQyTVoC
"""

#Single inheritance

class Car:
    def sound(self):
        print("Horn please")

class Toyota(Car):
    def bark(self):
        print("horn")

toyota = Toyota()
toyota.sound()

#Multiple Inheritance

class Animal:
    def sound(self):
        print("Animal makes a sound")

class Pet:
    def is_pet(self):
        print("This is a pet")

class Dog(Animal, Pet):
    def bark(self):
        print("Dog barks")

dog = Dog()
dog.sound()
dog.is_pet()
dog.bark()

#Multilevel Inheritance

class Animal:
    def type(self):
        print("Animal you can pet")

class pet(Animal):
    def good(self):
        print("dog is a good pet")

class Dog(pet):
    def bark(self):
        print("Dog barks")

dog = Dog()
dog.type()
dog.good()
dog.bark()

#Hierarchical Inheritance

class Animal:
    def sound(self):
        print("Animal makes a sound")

class Dog(Animal):
    def bark(self):
        print("Dog barks")

class Cat(Animal):
    def meow(self):
        print("Cat meows")

dog = Dog()
dog.sound()
dog.bark()

cat = Cat()
cat.sound()
cat.meow()

#Hybrid Inheritance

class Animal:
    def sound(self):
        print("Animal makes a sound")

class Mammal(Animal):
    def has_fur(self):
        print("Mammal has fur")

class Bird(Animal):
    def has_feathers(self):
        print("Bird has feathers")

class Bat(Mammal):
    def fly(self):
        print("Bat flies")

bat = Bat()
bird= Bird()
bat.sound()
bird.has_feathers()
bat.has_fur()
bat.fly()