# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-DjElOISbCaEYOKB9ZaHavz_jNIToeX
"""

#Method overriding in Python

class Shape:
    def area(self):
        print("Calculating area of the shape.")


class Circle(Shape):

    def area(self):
        print("Calculating area of the circle: πr²")


class Square(Shape):

    def area(self):
        print("Calculating area of the square: side²")


generic_shape = Shape()
circle = Circle()
square = Square()


generic_shape.area()
circle.area()
square.area()

Method overloading

class Student:

     def __init__(self,m1,m2):
         self.m1 = m1
         self.m2 = m2

     def sum(self,a=None,b=None,c=None):

         s = 0

         if a!=None and b!=None and c!=None:
           s = a+b+c
         elif a!=None and b!=None:
             s = a+b
         else:
             s = a

         return s


 s1 = Student(58,69)

 print(s1.sum(5,9))