# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mux5O7hkhcyT04dl9pR4ldb1q2MLx_rf

**Practice Question**
1. Check if the person is elible to Vote or not
"""

age = int(input("Enter your age"))
if age >= 18:
  print("Eligible for voting")
if age < 18 :
  print("Not eligible for voting")

"""2. Check if the Citizen is senior citizen or not"""

age = int(input("Enter your age"))
if age >= 60:
  print("Senior Citizen")
else:
    print("Not a Senior Citizen")

"""Match case :
matches the weekday number and return the weekday
"""

def weekday (m):
  match m :
    case 0 :
      return "Monday"
    case 1 :
      return "Tuesday"
    case 2 :
      return "Wednesday"
    case 3 :
      return "Thursday"
    case 4 :
      return "Friday"
    case 5 :
      return "Saturday"
    case 6 :
      return "Sunday"
    case default :
      return "Invalid day Number"

print(weekday(4))

"""**Functions**
1. To see sum of numbers in a list

"""

list_a = [2,5,6,7]
sum_result = sum(list_a)
print(list_a)
print(sum_result)



def maximum(a, b, c):

    if (a >= b) and (a >= c):
        largest = a

    elif (b >= a) and (b >= c):
        largest = b
    else:
        largest = c

    return largest


a = 20
b = 15
c = 12
print(maximum(a, b, c))

"""3. Multiplication of numbers in a list

"""

def multiply(numbers) :
  total =-42
  for x in numbers :
    total *= x
    return total
print(multiply((8, 2, 3, -1, 7)))