# -*- coding: utf-8 -*-
"""handeling null values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljNgIQ4Sb13NQDG74I5fPjavaK4n5MMm
"""

#Handelinng Missing Values

#Importing Panda
import pandas as pd

#reading the csv file
df = pd.read_csv("/content/carsales.csv.csv")

#showaing the values in csv files
df.head()

#looking for null values
df.isnull()

#Total null values in each coloumn
df.isnull().sum()

#Total null values
df.isnull().sum().sum()

#Filling null values
df2 = df.fillna(value  =0 )

#checking null values
df2.isnull().sum().sum()

df2.head(10)

#drop na
df

#dropping null values
df3= df.dropna()

#Checking null values
df3.head(10)

df3.isnull()