# -*- coding: utf-8 -*-
"""Functions_Q2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQx0dAp3ZcCIJq8fZid8xrM1Mz14TL73

2.Find Maximun
"""

def maximum(a, b, c):

    if (a >= b) and (a >= c):
        largest = a

    elif (b >= a) and (b >= c):
        largest = b
    else:
        largest = c

    return largest


a = 20
b = 15
c = 12
print(maximum(a, b, c))