# -*- coding: utf-8 -*-
"""Function_Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZspWwoZoq5eJioZEp-8WSSH5iGVrB5h-

1. To see sum of numbers in a list
"""

list_a = [2,5,6,7]
sum_result = sum(list_a)
print(list_a)
print(sum_result)