# -*- coding: utf-8 -*-
"""Functions_Q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2WvmFEOZjrjBeUfUmZKNHtHkPqI9RyN

3. Multiplication of numbers in a list
"""

def multiply(numbers) :
  total =-42
  for x in numbers :
    total *= x
    return total
print(multiply((8, 2, 3, -1, 7)))