# -*- coding: utf-8 -*-
"""Encapsulation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDX8PzFJF47mbi3HatX8Y9AbP0qijuSv

# Encapsulation in Python
Encapsulation is one of the fundemental concept of oops.It is desrcibes as wrapping of methods and varilbles in a class so any accidental modification can be avoided. Basically Python allows us to acces the data globbaly but my Encapsulation we can restrict the access to all the varibles and methods by making them private or protected.

**Real Life example :**
A university has Multiple faculties and each one of them teaches a different subject.Lets say Faculty A teaches HR and Faculty B teaches CS so both faculty will have access to student marks and performance related to the subject they teach. Supposedly faculty A wants to look at the performance of a student in the subject B teaches so to access the performance accordingly Faculty A need to ask Faculty B to grant access to student marks or performance in that particular subject.This is how Encapsulation works by basically restricting access to a certain methods and variables so that accidental modification can be avoided,

# **Coding example**
"""

class Smartphone:    #Defined class
   def __init__(self, brand, os): #Privatizing by using __
       self.brand = brand
       self.os = os

iphone = Smartphone("Apple", "iOS 17") #Object is created
print(iphone.os)