# -*- coding: utf-8 -*-
"""String Manupilation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVp6WWwAKc2OXyPmBxrU5eRyG2jDMKnC

# String Manupilation

1.Format Function
"""

name = "Mrigank"
marks = 90
result = 'Result {} ({})'.format(name, marks)
print(result)

"""2.Uppercase and lowercase"""

word="I love Football"
word.upper()

word = "I love Football"
word.lower()

"""3.is Function"""

word="289"
word.isnumeric()

word="289"
word.isdigit()

word="2.9"
word.isdecimal()

"""4.Starts or Ends with"""

word= "I love football"
word.startswith('I')

word= "I love football"
word.endswith('I')

"""5.Split Function"""

word="I love Football"
word.split(' ')