# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5XEguf-wc9YXFXFXoNir0p3ZUKjedgh

LOOPS

1. FOR LOOP
"""

for i in range(0,10,2):
  print(i)

"""2. WHILE LOOP"""

i=1
while i<=5:
  print(i)
  i+=1

"""3. DO WHILE LOOP"""

i = 1

while True :
  print(i)
  i=i+1
  if(i>5):
    break