# -*- coding: utf-8 -*-
"""cond_statement Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfjEvFKjCBQHF-BHiQ7R0Z7gAbvG58ZC

2. Check if the Citizen is senior citizen or not
"""

age = int(input("Enter your age"))
if age >= 60:
  print("Senior Citizen")
else:
    print("Not a Senior Citizen")