# -*- coding: utf-8 -*-
"""cond_statement Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGE2idj6QfelfuBmJ48kmXgXPwPCZblM

Q1.Check if the person is elible to Vote or not
"""

age = int(input("Enter your age"))
if age >= 18:
  print("Eligible for voting")
if age < 18 :
  print("Not eligible for voting")