# -*- coding: utf-8 -*-
"""Cond_StatementQ3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LE0jc1lUYyyjDf6SyQdnCcfD8pAoB5sy

Q3.Match case :
matches the weekday number and return the weekday
"""

def weekday (m):
  match m :
    case 0 :
      return "Monday"
    case 1 :
      return "Tuesday"
    case 2 :
      return "Wednesday"
    case 3 :
      return "Thursday"
    case 4 :
      return "Friday"
    case 5 :
      return "Saturday"
    case 6 :
      return "Sunday"
    case default :
      return "Invalid day Number"

print(weekday(4))